application: linguistics-lab
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /static
  static_dir: static
  
- url: /static
  static_dir: static

- url: /home
  script: plural2.app

- url: /root
  script: rootForm.app

- url: /plural2
  script: plural2.app






libraries:
- name: jinja2
  version: latest
- name: markupsafe                                                              
  version: latest 

builtins:
- remote_api: on

